import { BACKGROUND_DEFAULTS } from "./hero-background";

export const SCENE_FRAMING = { minHeight: 3.6, minWidth: 4.7 };

export const DEFAULT_SCENE_SETTINGS = {
  ...BACKGROUND_DEFAULTS,
  autoQuality: true,
  fpsThreshold: 40,
  fpsDuration: 3,
  cameraX: 1.7,
  cameraY: 24.4,
  cameraZ: 55,
  targetY: 6.25,
  zoom: 1.06,
  tilt: 11.5,
  keyLight: 0.9,
  fillLight: 3,
  rimLight: 1.5,
  greenLight: 6,
  redLight: 6,
  environmentIntensity: 1.3,
  environmentBlur: 0.09,
  roughness: 0.075,
  transmission: 1,
  thickness: 0.52,
  ior: 1.17,
  attenuationDistance: 15.8,
  greenTint: "#51ea27",
  redTint: "#ff0000",
  contours: true,
  rimShimmer: true,
  rimShimmerInterval: 7,
  rimShimmerDuration: 7.5,
  rimShimmerStrength: 1.95,
  parallax: true,
  parallaxStrength: 0.19,
  rotationDamping: 4,
  hover: true,
  hoverDamping: 8,
  exposure: 0.72,
  dprLimit: 2,
  transmissionResolution: 1,
};

export type SceneSettings = typeof DEFAULT_SCENE_SETTINGS;
